spring:
  application:
    name: authentication
  h2:
    console:
      enabled: true

server:
  port: ${SERVER_PORT}

grpc:
  client:
    database:
      address: ${GRPC_DATABASE_URL}:${GRPC_DATABASE_PORT}
      negotiation-type: plaintext
  server:
    port: ${GRPC_PORT}


token:
  seed: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A753278554E0A2D3B5F2D78F247D1F6E5C3A596D64YET3BH2HH9845GP94G9824H3EGO1IT98347ERTR4GH459845HT2TG
  token-validity: 1800000
