spring:
  application:
    name: gateway
  security:
    user:
      password: password
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

gateway:
  secret: ${SECRET}

grpc:
  client:
    backend:
      address: ${GRPC_BACKEND_URL}:${GRPC_BACKEND_PORT}
      negotiation-type: plaintext
    auth:
      address: ${GRPC_AUTH_URL}:${GRPC_AUTH_PORT}
      negotiation-type: plaintext
